const allDestinations = [
    {
        id: 'bora-bora',
        name: 'Bora Bora, French Polynesia',
        type: 'island',
        fears: ['water', 'insects', 'flying'],
        description: 'A stunning island known for its turquoise lagoon, coral reefs, and overwater bungalows.',
        budget: 'Approx. $3500 for a 5-day trip.',
        budgetLevel: 'luxury',
        image: 'https://images.unsplash.com/photo-1507525428034-b723a9ce6890?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Tropical and sunny year-round, with an average temperature of 80°F (27°C).',
        mustTryFood: ['Poisson Cru', 'Ma\'a Tinito', 'Uru (Breadfruit)'],
        mustVisitPlaces: ['Mount Otemanu', 'Matira Beach', 'Coral Gardens']
    },
    {
        id: 'kyoto',
        name: 'Kyoto, Japan',
        type: 'historical',
        fears: ['crowds'],
        description: 'A city of ancient temples, serene gardens, and traditional geishas.',
        budget: 'Approx. $2000 for a 7-day trip.',
        budgetLevel: 'mid',
        image: 'https://images.unsplash.com/photo-1524413840807-0c3cb6fa808d?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Mild winters and hot, humid summers. Best visited in spring or fall.',
        mustTryFood: ['Kaiseki', 'Yudofu', 'Matcha sweets'],
        mustVisitPlaces: ['Kinkaku-ji (Golden Pavilion)', 'Fushimi Inari-taisha Shrine', 'Arashiyama Bamboo Grove']
    },
    {
        id: 'rome',
        name: 'Rome, Italy',
        type: 'city',
        fears: ['crowds'],
        description: 'The eternal city, filled with ancient ruins, stunning art, and vibrant street life.',
        budget: 'Approx. $1800 for a 4-day trip.',
        budgetLevel: 'mid',
        image: 'https://images.unsplash.com/photo-1552832230-c0197dd311b5?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=796&q=80',
        weather: 'Mediterranean climate with hot summers and mild, rainy winters.',
        mustTryFood: ['Cacio e Pepe', 'Carbonara', 'Supplì'],
        mustVisitPlaces: ['Colosseum', 'Vatican City (St. Peter\'s Basilica, Sistine Chapel)', 'Trevi Fountain']
    },
    {
        id: 'amazon',
        name: 'Amazon Rainforest, Brazil',
        type: 'forest',
        fears: ['insects', 'animals', 'dark'],
        description: 'The world\'s largest tropical rainforest, teeming with incredible biodiversity.',
        budget: 'Approx. $1000 for a 3-day guided tour.',
        budgetLevel: 'budget',
        image: 'https://images.unsplash.com/photo-1593522943529-332d71fb3362?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Hot and humid year-round, with a distinct rainy season.',
        mustTryFood: ['Açaí bowls', 'Pão de Queijo', 'Feijoada'],
        mustVisitPlaces: ['Anavilhanas Archipelago', 'Meeting of Waters', 'Jungle lodges']
    },
    {
        id: 'sahara',
        name: 'Sahara Desert, Morocco',
        type: 'desert',
        fears: ['dark', 'enclosed', 'animals'],
        description: 'Experience the vast, stunning landscapes of the world\'s largest hot desert.',
        budget: 'Approx. $900 for a 3-day desert tour.',
        budgetLevel: 'budget',
        image: 'https://images.unsplash.com/photo-1516370873344-fb7c61054fa0?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Extremely hot days and cool nights. Best visited in cooler months.',
        mustTryFood: ['Tagine', 'Couscous', 'Mint Tea'],
        mustVisitPlaces: ['Erg Chebbi dunes', 'Ait Benhaddou', 'Dades Gorges']
    },
    {
        id: 'interlaken',
        name: 'Interlaken, Switzerland',
        type: 'mountain',
        fears: ['heights'],
        description: 'A picturesque town nestled between two alpine lakes, perfect for adventure sports.',
        budget: 'Approx. $2200 for a 5-day trip.',
        budgetLevel: 'luxury',
        image: 'https://images.unsplash.com/photo-1530924472363-334458a63838?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Cool summers and cold, snowy winters. Ideal for both summer and winter sports.',
        mustTryFood: ['Cheese Fondue', 'Rösti', 'Swiss Chocolate'],
        mustVisitPlaces: ['Jungfraujoch (Top of Europe)', 'Harder Kulm', 'Lake Thun & Lake Brienz']
    },
    {
        id: 'scottish-highlands',
        name: 'Scottish Highlands, Scotland',
        type: 'countryside',
        fears: ['dark', 'water'],
        description: 'Dramatic landscapes of mountains, lochs, and ancient castles.',
        budget: 'Approx. $1500 for a 6-day road trip.',
        budgetLevel: 'mid',
        image: 'https://images.unsplash.com/photo-1598435120604-1a4a70d4383a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Changeable, often misty and cool. Pack layers!',
        mustTryFood: ['Haggis', 'Scottish Salmon', 'Cullen Skink'],
        mustVisitPlaces: ['Loch Ness', 'Isle of Skye', 'Eilean Donan Castle']
    },
    {
        id: 'santorini',
        name: 'Santorini, Greece',
        type: 'beach',
        fears: ['heights', 'crowds'],
        description: 'Famous for its stunning sunsets, white-washed villages, and volcanic beaches.',
        budget: 'Approx. $2800 for a 5-day trip.',
        budgetLevel: 'luxury',
        image: 'https://images.unsplash.com/photo-1589249257939-12349243e3a3?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Hot, sunny summers and mild winters.',
        mustTryFood: ['Fava', 'Tomato Keftedes', 'Fresh Seafood'],
        mustVisitPlaces: ['Oia Village', 'Red Beach', 'Akrotiri Archaeological Site']
    },
    {
        id: 'lake-como',
        name: 'Lake Como, Italy',
        type: 'lake',
        fears: ['water'],
        description: 'A stunning alpine lake with picturesque villages and opulent villas.',
        budget: 'Approx. $2500 for a 4-day trip.',
        budgetLevel: 'luxury',
        image: 'https://images.unsplash.com/photo-1528127269322-539801943592?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Warm summers and cool winters. Best visited from April to October.',
        mustTryFood: ['Risotto con Pesce Persico', 'Polenta', 'Local Cheeses'],
        mustVisitPlaces: ['Bellagio', 'Villa Carlotta', 'Varenna']
    },
    {
        id: 'zermatt',
        name: 'Zermatt, Switzerland',
        type: 'snowy',
        fears: ['heights', 'enclosed'],
        description: 'A world-famous ski resort at the foot of the iconic Matterhorn.',
        budget: 'Approx. $3000 for a 5-day ski trip.',
        budgetLevel: 'luxury',
        image: 'https://images.unsplash.com/photo-1585381828421-245ffb0a811a?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Cold, snowy winters perfect for skiing. Cool summers for hiking.',
        mustTryFood: ['Fondue', 'Raclette', 'Valaisanne-style dried meats'],
        mustVisitPlaces: ['Matterhorn Glacier Paradise', 'Gornergrat Railway', 'Sunnegga']
    },
    {
        id: 'mount-bromo',
        name: 'Mount Bromo, Indonesia',
        type: 'volcano',
        fears: ['heights', 'dark'],
        description: 'An active volcano in East Java, known for its spectacular sunrise views.',
        budget: 'Approx. $700 for a 2-day tour.',
        budgetLevel: 'budget',
        image: 'https://images.unsplash.com/photo-1596623361463-eac875cb4537?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Cool and often misty. Temperatures can drop significantly at night.',
        mustTryFood: ['Nasi Goreng', 'Sate Ayam', 'Bakso'],
        mustVisitPlaces: ['Bromo Tengger Semeru National Park', 'Penanjakan Viewpoint', 'Madakaripura Waterfall']
    },
    {
        id: 'monteverde',
        name: 'Monteverde, Costa Rica',
        type: 'rainforest',
        fears: ['insects', 'spiders', 'heights'],
        description: 'A lush cloud forest reserve, famous for its biodiversity and hanging bridges.',
        budget: 'Approx. $1200 for a 4-day trip.',
        budgetLevel: 'mid',
        image: 'https://images.unsplash.com/photo-1569394293123-2a3a2a1a3a47?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Mild and humid, with a misty "cloud forest" feel. Rainy season from May to November.',
        mustTryFood: ['Gallo Pinto', 'Casado', 'Fresh Tropical Fruits'],
        mustVisitPlaces: ['Monteverde Cloud Forest Reserve', 'Sky Walk (Hanging Bridges)', 'Curi-Cancha Reserve']
    },
    {
        id: 'serengeti',
        name: 'Serengeti National Park, Tanzania',
        type: 'safari',
        fears: ['animals', 'insects', 'isolation'],
        description: 'Home to the Great Migration, offering unparalleled wildlife viewing.',
        budget: 'Approx. $4000 for a 4-day safari.',
        budgetLevel: 'luxury',
        image: 'https://images.unsplash.com/photo-1534437431097-8257c49b2e90?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Generally dry and warm, with two rainy seasons.',
        mustTryFood: ['Ugali', 'Nyama Choma', 'Mandazi'],
        mustVisitPlaces: ['Seronera River Valley', 'Ngorongoro Crater', 'Olduvai Gorge']
    },
    {
        id: 'tuscany',
        name: 'Tuscany, Italy',
        type: 'vineyard',
        fears: ['insects'],
        description: 'Rolling hills, charming vineyards, and a rich history of art and cuisine.',
        budget: 'Approx. $2200 for a 6-day trip.',
        budgetLevel: 'mid',
        image: 'https://images.unsplash.com/photo-1568942395449-04d3a3a899f7?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Hot summers and mild, pleasant spring and autumn seasons.',
        mustTryFood: ['Bistecca alla Fiorentina', 'Pappa al Pomodoro', 'Chianti Wine'],
        mustVisitPlaces: ['Florence', 'Siena', 'Val d\'Orcia']
    },
    {
        id: 'svalbard',
        name: 'Svalbard, Norway',
        type: 'arctic',
        fears: ['dark', 'isolation', 'animals'],
        description: 'A remote archipelago known for its polar bears, glaciers, and the Northern Lights.',
        budget: 'Approx. $3500 for a 5-day expedition.',
        budgetLevel: 'luxury',
        image: 'https://images.unsplash.com/photo-1579582933725-3357d111f434?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=870&q=80',
        weather: 'Arctic climate. Cold year-round with polar night in winter and midnight sun in summer.',
        mustTryFood: ['Reindeer steak', 'Seal meat', 'Arctic char'],
        mustVisitPlaces: ['Longyearbyen', 'Svalbard Global Seed Vault', 'Ice Caves']
    },
    {
        id: 'maldives',
        name: 'The Maldives',
        type: 'tropical',
        fears: ['water', 'flying'],
        description: 'A tropical paradise of over 1,000 coral islands with pristine beaches and clear waters.',
        budget: 'Approx. $4500 for a 7-day stay.',
        budgetLevel: 'luxury',
        image: 'https://images.unsplash.com/photo-1512100356356-de1b84283e18?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=875&q=80',
        weather: 'Hot and sunny year-round, with a dry season from December to April.',
        mustTryFood: ['Garudhiya', 'Mas Huni', 'Bis Keemiya'],
        mustVisitPlaces: ['Malé', 'Utheemu Ganduvaru', 'Banana Reef']
    }
];
